FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim-arm64v8 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ON.Authentication/Shared ON.Authentication/Shared
COPY ON.Backup/SimpleBackup ON.Backup/SimpleBackup
COPY ON.Fragment ON.Fragment
RUN dotnet restore "ON.Backup/SimpleBackup/Service/ON.Backup.SimpleBackup.Service.csproj"
WORKDIR "/src/ON.Backup/SimpleBackup/Service"
RUN dotnet build "ON.Backup.SimpleBackup.Service.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ON.Backup.SimpleBackup.Service.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ON.Backup.SimpleBackup.Service.dll"]