version: '3'
services:
  cmsservice:
    image: opennetwork/simplecms-service:linux-amd64
    depends_on:
      - authservice
      - settingsservice
      - statsservice
    expose:
      - 80
    ports:
      - $CMS_PORT:$CMS_PORT
    env_file:
      - environment.${ENVIRONMENT_FILE}.env
      - ports.env
      - services.${SERVICES_FILE}.env
    environment:
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - VIRTUAL_PORT=80
      - VIRTUAL_PATH=~^/api/cms
      - JWT_PUB_KEY=$JWT_PUB_KEY
    logging:
      options:
        max-size: "10m"
    restart: always
    volumes:
      - ${DATA_LOC}/cms:/data
