version: '3'
services:
  commentservice:
    image: opennetwork/simplecomment-service:linux-amd64
    depends_on:
      - authservice
      - eventdb
    expose:
      - 80
    ports:
      - $COMMENT_PORT:$COMMENT_PORT
    env_file:
      - environment.${ENVIRONMENT_FILE}.env
      - ports.env
      - services.${SERVICES_FILE}.env
    environment:
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - VIRTUAL_PORT=80
      - VIRTUAL_PATH=~^/api/comment
      - JWT_PUB_KEY=$JWT_PUB_KEY
    logging:
      options:
        max-size: "10m"
    restart: always
    volumes:
      - ${DATA_LOC}/comment:/data
