version: '3'
services:
  paymentservice:
    image: opennetwork/payment-service:linux-amd64
    depends_on:
      - settingsservice
    expose:
      - 80
    ports:
      - $PAYMENT_PORT:$PAYMENT_PORT
    env_file:
      - environment.${ENVIRONMENT_FILE}.env
      - ports.env
      - services.${SERVICES_FILE}.env
    environment:
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - VIRTUAL_PORT=80
      - VIRTUAL_PATH=~^/api/payment
      - JWT_PUB_KEY=$JWT_PUB_KEY
    restart: always
    volumes:
      - ${DATA_LOC}/payment:/data
