version: '3'
services:
  web:
    image: opennetwork/simpleweb:linux-amd64
    ports:
      - 8002:80
    env_file:
      - environment.${ENVIRONMENT_FILE}.env
      - ports.env
      - services.${SERVICES_FILE}.env
    environment:
      - JWT_PUB_KEY=$JWT_PUB_KEY
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - VIRTUAL_PORT=80
      - VIRTUAL_PATH=/
