FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim-arm64v8 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ON.Authentication/Shared ON.Authentication/Shared
COPY ON.Authorization/SimplePayments ON.Authorization/SimplePayments
COPY ON.Fragment ON.Fragment
RUN dotnet restore "ON.Authorization/SimplePayments/Service/ON.Authorization.SimplePayments.Service.csproj"
WORKDIR "/src/ON.Authorization/SimplePayments/Service"
RUN dotnet build "ON.Authorization.SimplePayments.Service.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ON.Authorization.SimplePayments.Service.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ON.Authorization.SimplePayments.Service.dll"]
