FROM mcr.microsoft.com/dotnet/aspnet:5.0.8-buster-slim-amd64 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY NodeF.Authentication/Shared NodeF.Authentication/Shared
COPY NodeF.Authentication/SimpleAuth NodeF.Authentication/SimpleAuth
COPY NodeF.Fragment NodeF.Fragment
RUN dotnet restore "NodeF.Authentication/SimpleAuth/Service/NodeF.Authentication.SimpleAuth.Service.csproj"
WORKDIR "/src/NodeF.Authentication/SimpleAuth/Service"
RUN dotnet build "NodeF.Authentication.SimpleAuth.Service.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "NodeF.Authentication.SimpleAuth.Service.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY assets/nodef.localhost.pfx .
RUN rm appsettings.Development.json; exit 0
ENV ASPNETCORE_URLS=http://+:80
ENV ASPNETCORE_Kestrel__Certificates__Default__Password=nodef
ENV ASPNETCORE_Kestrel__Certificates__Default__Path=/app/nodef.localhost.pfx
ENTRYPOINT ["dotnet", "NodeF.Authentication.SimpleAuth.Service.dll"]