FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine-arm64v8 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY NodeF.Authentication/Shared NodeF.Authentication/Shared
COPY NodeF.Authentication/SimpleAuth NodeF.Authentication/SimpleAuth
COPY NodeF.Fragment NodeF.Fragment
RUN dotnet restore "NodeF.Authentication/SimpleAuth/Service/NodeF.Authentication.SimpleAuth.Service.csproj"
WORKDIR "/src/NodeF.Fragment"
RUN dotnet build
WORKDIR "/src/NodeF.Authentication/SimpleAuth/Service"
RUN dotnet build "NodeF.Authentication.SimpleAuth.Service.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "NodeF.Authentication.SimpleAuth.Service.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "NodeF.Authentication.SimpleAuth.Service.dll"]