FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim-arm32v7 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY NodeF.Authentication/Shared NodeF.Authentication/Shared
COPY NodeF.Content/SimpleCMS NodeF.Content/SimpleCMS
COPY NodeF.Fragment NodeF.Fragment
RUN dotnet restore "NodeF.Content/SimpleCMS/Service/NodeF.Content.SimpleCMS.Service.csproj"
WORKDIR "/src/NodeF.Content/SimpleCMS/Service"
RUN dotnet build "NodeF.Content.SimpleCMS.Service.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "NodeF.Content.SimpleCMS.Service.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "NodeF.Content.SimpleCMS.Service.dll"]