FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal-arm64v8 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ON.Authentication/Shared ON.Authentication/Shared
COPY ON.Authorization/Paypal ON.Authorization/Paypal
COPY ON.Fragment ON.Fragment
COPY ON.Crypto ON.Crypto
RUN dotnet restore "ON.Authorization/Paypal/Web/ON.Authorization.Paypal.Web.csproj"
WORKDIR "/src/ON.Authorization/Paypal/Web"
RUN dotnet build "ON.Authorization.Paypal.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ON.Authorization.Paypal.Web.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ON.Authorization.Paypal.Web.dll"]
