FROM mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim-arm64v8 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ON.Authentication/Shared ON.Authentication/Shared
COPY ON.Authentication/SimpleAuth ON.Authentication/SimpleAuth
COPY ON.Fragment ON.Fragment
COPY ON.Crypto ON.Crypto
RUN dotnet restore "ON.Authentication/SimpleAuth/Web/ON.Authentication.SimpleAuth.Web.csproj"
WORKDIR "/src/ON.Authentication/SimpleAuth/Web"
RUN dotnet build "ON.Authentication.SimpleAuth.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ON.Authentication.SimpleAuth.Web.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ON.Authentication.SimpleAuth.Web.dll"]