version: '3'
services:
  tor:
    image: goldy/tor-hidden-service:0.3.5.8
    links:
      - web
    environment:
      - SERVICE1_TOR_SERVICE_HOSTS=80:web:80
      - SERVICE1_TOR_SERVICE_VERSION=3
      - SERVICE1_TOR_SERVICE_KEY=PT0gZWQyNTUxOXYxLXNlY3JldDogdHlwZTAgPT0AAACoJv33hb1ZZ2hkEDs9iQLblAr2uMI/PgYWtn/J2dTHbqeYcdj6a7/g5ISIcq6oNbnaMVhueke7e71M/NRFdI6h
#  nginx-proxy:
#    image: nginxproxy/nginx-proxy:dev-alpine
#    ports:
#      - "8002:80"
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock:ro
  web:
    image: opennetwork/simpleweb:linux-amd64
    ports:
      - "8002:80"
    environment:
#      - VIRTUAL_HOST=localhost,bc5wgzqo4wwoqek773ohqfgfaenlbctvokdeksofcqzrtgsoneryx5id.onion
#      - VIRTUAL_PORT=80
#      - VIRTUAL_PATH=/
      - JWT_PUB_KEY=eyJBZGRpdGlvbmFsRGF0YSI6e30sIkFsZyI6IkVTMjU2IiwiQ3J2IjoiUC0yNTYiLCJEIjpudWxsLCJEUCI6bnVsbCwiRFEiOm51bGwsIkUiOm51bGwsIksiOm51bGwsIktleUlkIjoiZjYwYjIzZDctYTdiYy00MmNjLWE0YjQtZTdiZjI0ODZiYzg5IiwiS2V5T3BzIjpbXSwiS2lkIjoiZjYwYjIzZDctYTdiYy00MmNjLWE0YjQtZTdiZjI0ODZiYzg5IiwiS3R5IjoiRUMiLCJOIjpudWxsLCJPdGgiOm51bGwsIlAiOm51bGwsIlEiOm51bGwsIlFJIjpudWxsLCJVc2UiOiJzaWciLCJYIjoiVDNCQzlQUlNkamFIcEV4VXF6Z1RpMWt5X2pvMG9YSHMtbVNoN0RsRVZFMCIsIlg1YyI6W10sIlg1dCI6bnVsbCwiWDV0UzI1NiI6bnVsbCwiWDV1IjpudWxsLCJZIjoiMjhmNEtLS0hyZ3dfM2Z4SlJsX1c0eExkcm5FUXVPQWNfZ0wyN0tNc0NSOCIsIktleVNpemUiOjI1NiwiSGFzUHJpdmF0ZUtleSI6ZmFsc2UsIkNyeXB0b1Byb3ZpZGVyRmFjdG9yeSI6eyJDcnlwdG9Qcm92aWRlckNhY2hlIjp7fSwiQ3VzdG9tQ3J5cHRvUHJvdmlkZXIiOm51bGwsIkNhY2hlU2lnbmF0dXJlUHJvdmlkZXJzIjp0cnVlfX0
      - SERVICE__AUTHSERVICE__GRPC__HOST=host.docker.internal
      - SERVICE__AUTHSERVICE__GRPC__PORT=7001
      - SERVICE__CMSSERVICE__GRPC__HOST=host.docker.internal
      - SERVICE__CMSSERVICE__GRPC__PORT=7002
      - SERVICE__FAKEPAYSERVICE__GRPC__HOST=host.docker.internal
      - SERVICE__FAKEPAYSERVICE__GRPC__PORT=7003
      - SERVICE__SETTINGSSERVICE__GRPC__HOST=host.docker.internal
      - SERVICE__SETTINGSSERVICE__GRPC__PORT=7004
