version: '3'
include:
  - path: ../common/web.yml

services:
  tor:
    image: goldy/tor-hidden-service:0.3.5.8
    links:
      - web
    environment:
      - SERVICE1_TOR_SERVICE_HOSTS=80:web:80
      - SERVICE1_TOR_SERVICE_VERSION=3
      - SERVICE1_TOR_SERVICE_KEY=PT0gZWQyNTUxOXYxLXNlY3JldDogdHlwZTAgPT0AAACoJv33hb1ZZ2hkEDs9iQLblAr2uMI/PgYWtn/J2dTHbqeYcdj6a7/g5ISIcq6oNbnaMVhueke7e71M/NRFdI6h
