version: '3.1'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:dev-alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  authweb:
    image: opennetwork/simpleauth-web:linux-amd64
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${DNSNAME}
      - VIRTUAL_PORT=80
      - VIRTUAL_PATH=~^/(auth|changepassword|login|logout|register|settings|subscription)
      - JWT_PUB_KEY=${JWTPUB}
      - SUBSCRIPTION_TIERS=${SUBSCRIPTION_TIERS}
      - WEBSITE_NAME=${WEBSITE_NAME}
      - SERVICE__AUTHSERVICE__HOST=authservice
      - SERVICE__AUTHSERVICE__PORT=80
      - ASPNETCORE_ENVIRONMENT=Development
      
  authservice:
    image: opennetwork/simpleauth-web:linux-amd64
    expose:
      - "80"
    environment:
      - JWT_PRIV_KEY=${JWTPRIV}
      - JWT_PUB_KEY=${JWTPUB}
      - SERVICE__FAKEPAYSERVICE__HOST=fakepayservice
      - SERVICE__FAKEPAYSERVICE__PORT=80
      
  cmsweb:
    image: opennetwork/simplecms-web:linux-amd64
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${DNSNAME}
      - VIRTUAL_PORT=80
      - VIRTUAL_PATH=/
      - JWT_PUB_KEY=${JWTPUB}
      - WEBSITE_NAME=${WEBSITE_NAME}
      - WEBSITE_DESC=${WEBSITE_DESC}
      - SERVICE__CMSSERVICE__HOST=cmsservice
      - SERVICE__CMSSERVICE__PORT=80
      
  cmsservice:
    image: opennetwork/simplecms-service:linux-amd64
    expose:
      - "80"
    environment:
      - JWT_PUB_KEY=${JWTPUB}
      
  fakepayweb:
    image: opennetwork/fakepayments-web:linux-amd64
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${DNSNAME}
      - VIRTUAL_PORT=80
      - VIRTUAL_PATH=~^/subscription/fake
      - JWT_PUB_KEY=${JWTPUB}
      - SUBSCRIPTION_TIERS=${SUBSCRIPTION_TIERS}
      - WEBSITE_NAME=${WEBSITE_NAME}
      - SERVICE__CMSSERVICE__HOST=cmsservice
      - SERVICE__CMSSERVICE__PORT=80
      - SERVICE__FAKEPAYSERVICE__HOST=fakepayservice
      - SERVICE__FAKEPAYSERVICE__PORT=80
      
  fakepayservice:
    image: opennetwork/fakepayments-service:linux-amd64
    expose:
      - "80"
    environment:
      - JWT_PUB_KEY=${JWTPUB}
