FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim-arm64v8 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ON.Authentication/Shared ON.Authentication/Shared
COPY ON.Content/SimpleCMS ON.Content/SimpleCMS
COPY ON.Fragment ON.Fragment
RUN dotnet restore "ON.Content/SimpleCMS/Web/ON.Content.SimpleCMS.Web.csproj"
WORKDIR "/src/ON.Content/SimpleCMS/Web"
RUN dotnet build "ON.Content.SimpleCMS.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ON.Content.SimpleCMS.Web.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ON.Content.SimpleCMS.Web.dll"]