FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim-arm64v8 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY NodeF.Authentication/Shared NodeF.Authentication/Shared
COPY NodeF.Authorization/SimplePayments NodeF.Authorization/SimplePayments
COPY NodeF.Fragment NodeF.Fragment
RUN dotnet restore "NodeF.Authorization/SimplePayments/Service/NodeF.Authorization.SimplePayments.Service.csproj"
WORKDIR "/src/NodeF.Authorization/SimplePayments/Service"
RUN dotnet build "NodeF.Authorization.SimplePayments.Service.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "NodeF.Authorization.SimplePayments.Service.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "NodeF.Authorization.SimplePayments.Service.dll"]
