FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal-arm64v8 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ON.Authentication/Shared ON.Authentication/Shared
COPY ON.Fragment ON.Fragment
COPY ON.Crypto ON.Crypto
COPY ON.Settings ON.Settings
COPY ON.Notification/SimpleNotification ON.Notification/SimpleNotification
RUN dotnet restore "ON.Notification/SimpleNotification/Service/ON.Notification.SimpleNotification.Service.csproj"
WORKDIR "/src/ON.Notification/SimpleNotification/Service"
RUN rm -f appsettings.Development.json
RUN dotnet build "ON.Notification.SimpleNotification.Service.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ON.Notification.SimpleNotification.Service.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS=http://+:80
ENTRYPOINT ["dotnet", "ON.Notification.SimpleNotification.Service.dll"]
